<?php
declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * ShopCountries seed.
 */
class ShopCountriesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'iso2' => 'AD',
                'iso3' => 'AND',
                'name' => 'Andorra',
                'name_de' => 'Andorra',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 2,
                'iso2' => 'AE',
                'iso3' => 'ARE',
                'name' => 'United Arab Emirates',
                'name_de' => 'Vereinigte Arabische Emirate',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 3,
                'iso2' => 'AF',
                'iso3' => 'AFG',
                'name' => 'Afghanistan',
                'name_de' => 'Afghanistan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 4,
                'iso2' => 'AG',
                'iso3' => 'ATG',
                'name' => 'Antigua and Barbuda',
                'name_de' => 'Antigua und Barbuda',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 5,
                'iso2' => 'AI',
                'iso3' => 'AIA',
                'name' => 'Anguilla',
                'name_de' => 'Anguilla',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 6,
                'iso2' => 'AL',
                'iso3' => 'ALB',
                'name' => 'Albania',
                'name_de' => 'Albanien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 7,
                'iso2' => 'AM',
                'iso3' => 'ARM',
                'name' => 'Armenia',
                'name_de' => 'Armenien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 8,
                'iso2' => 'AN',
                'iso3' => 'ANT',
                'name' => 'Netherlands Antilles',
                'name_de' => 'Niederländische Antillen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 9,
                'iso2' => 'AO',
                'iso3' => 'AGO',
                'name' => 'Angola',
                'name_de' => 'Angola',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 10,
                'iso2' => 'AQ',
                'iso3' => 'ATA',
                'name' => 'Antarctica',
                'name_de' => 'Antarktis',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 11,
                'iso2' => 'AR',
                'iso3' => 'ARG',
                'name' => 'Argentina',
                'name_de' => 'Argentinien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 12,
                'iso2' => 'AS',
                'iso3' => 'ASM',
                'name' => 'American Samoa',
                'name_de' => 'Amerikanisch Samoa',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 13,
                'iso2' => 'AT',
                'iso3' => 'AUT',
                'name' => 'Austria',
                'name_de' => 'Österreich',
                'priority' => 1,
                'is_published' => 1,
            ],
            [
                'id' => 14,
                'iso2' => 'AU',
                'iso3' => 'AUS',
                'name' => 'Australia',
                'name_de' => 'Australien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 15,
                'iso2' => 'AW',
                'iso3' => 'ABW',
                'name' => 'Aruba',
                'name_de' => 'Aruba',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 16,
                'iso2' => 'AX',
                'iso3' => 'ALA',
                'name' => 'Aland Islands',
                'name_de' => 'Aland Inseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 17,
                'iso2' => 'AZ',
                'iso3' => 'AZE',
                'name' => 'Azerbaijan',
                'name_de' => 'Aserbaidschan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 18,
                'iso2' => 'BA',
                'iso3' => 'BIH',
                'name' => 'Bosnia and Herzegovina',
                'name_de' => 'Bosnien und Herzegowin',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 19,
                'iso2' => 'BB',
                'iso3' => 'BRB',
                'name' => 'Barbados',
                'name_de' => 'Barbados',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 20,
                'iso2' => 'BD',
                'iso3' => 'BGD',
                'name' => 'Bangladesh',
                'name_de' => 'Bangladesch',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 21,
                'iso2' => 'BE',
                'iso3' => 'BEL',
                'name' => 'Belgium',
                'name_de' => 'Belgien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 22,
                'iso2' => 'BF',
                'iso3' => 'BFA',
                'name' => 'Burkina Faso',
                'name_de' => 'Burkina Faso',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 23,
                'iso2' => 'BG',
                'iso3' => 'BGR',
                'name' => 'Bulgaria',
                'name_de' => 'Bulgarien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 24,
                'iso2' => 'BH',
                'iso3' => 'BHR',
                'name' => 'Bahrain',
                'name_de' => 'Bahrain',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 25,
                'iso2' => 'BI',
                'iso3' => 'BDI',
                'name' => 'Burundi',
                'name_de' => 'Burundi',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 26,
                'iso2' => 'BJ',
                'iso3' => 'BEN',
                'name' => 'Benin',
                'name_de' => 'Benin',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 27,
                'iso2' => 'BL',
                'iso3' => 'BLM',
                'name' => 'St. Barthélemy',
                'name_de' => 'St. Barthélemy',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 28,
                'iso2' => 'BM',
                'iso3' => 'BMU',
                'name' => 'Bermuda',
                'name_de' => 'Bermuda',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 29,
                'iso2' => 'BN',
                'iso3' => 'BRN',
                'name' => 'Brunei Darussalam',
                'name_de' => 'Brunei Darussalam',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 30,
                'iso2' => 'BO',
                'iso3' => 'BOL',
                'name' => 'Bolivia',
                'name_de' => 'Bolivien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 31,
                'iso2' => 'BR',
                'iso3' => 'BRA',
                'name' => 'Brazil',
                'name_de' => 'Brasilien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 32,
                'iso2' => 'BS',
                'iso3' => 'BHS',
                'name' => 'Bahamas',
                'name_de' => 'Bahamas',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 33,
                'iso2' => 'BT',
                'iso3' => 'BTN',
                'name' => 'Bhutan',
                'name_de' => 'Bhutan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 34,
                'iso2' => 'BV',
                'iso3' => 'BVT',
                'name' => 'Bouvet Island',
                'name_de' => 'Bouvetinsel',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 35,
                'iso2' => 'BW',
                'iso3' => 'BWA',
                'name' => 'Botswana',
                'name_de' => 'Botsuana',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 36,
                'iso2' => 'BY',
                'iso3' => 'BLR',
                'name' => 'Belarus',
                'name_de' => 'Weißrussland',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 37,
                'iso2' => 'BZ',
                'iso3' => 'BLZ',
                'name' => 'Belize',
                'name_de' => 'Belize',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 38,
                'iso2' => 'CA',
                'iso3' => 'CAN',
                'name' => 'Canada',
                'name_de' => 'Kanada',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 39,
                'iso2' => 'CC',
                'iso3' => 'CCK',
                'name' => 'Cocos (Keeling) Islands',
                'name_de' => 'Kokosinseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 40,
                'iso2' => 'CD',
                'iso3' => 'COD',
                'name' => 'Congo, The Democratic Republic of The',
                'name_de' => 'Kongo, Dem. Rep.',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 41,
                'iso2' => 'CF',
                'iso3' => 'CAF',
                'name' => 'Central African Republic',
                'name_de' => 'Zentralafrikanische Republik',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 42,
                'iso2' => 'CG',
                'iso3' => 'COG',
                'name' => 'Congo',
                'name_de' => 'Kongo',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 43,
                'iso2' => 'CH',
                'iso3' => 'CHE',
                'name' => 'Switzerland',
                'name_de' => 'Schweiz',
                'priority' => 1,
                'is_published' => 0,
            ],
            [
                'id' => 44,
                'iso2' => 'CI',
                'iso3' => 'CIV',
                'name' => 'Cote D\'ivoire',
                'name_de' => 'C\'te d\'Ivoire',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 45,
                'iso2' => 'CK',
                'iso3' => 'COK',
                'name' => 'Cook Islands',
                'name_de' => 'Cookinseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 46,
                'iso2' => 'CL',
                'iso3' => 'CHL',
                'name' => 'Chile',
                'name_de' => 'Chile',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 47,
                'iso2' => 'CM',
                'iso3' => 'CMR',
                'name' => 'Cameroon',
                'name_de' => 'Kamerun',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 48,
                'iso2' => 'CN',
                'iso3' => 'CHN',
                'name' => 'China',
                'name_de' => 'China',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 49,
                'iso2' => 'CO',
                'iso3' => 'COL',
                'name' => 'Colombia',
                'name_de' => 'Kolumbien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 50,
                'iso2' => 'CR',
                'iso3' => 'CRI',
                'name' => 'Costa Rica',
                'name_de' => 'Costa Rica',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 51,
                'iso2' => 'CU',
                'iso3' => 'CUB',
                'name' => 'Cuba',
                'name_de' => 'Kuba',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 52,
                'iso2' => 'CV',
                'iso3' => 'CPV',
                'name' => 'Cape Verde',
                'name_de' => 'Kap Verde',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 53,
                'iso2' => 'CX',
                'iso3' => 'CXR',
                'name' => 'Christmas Island',
                'name_de' => 'Weihnachtsinsel',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 54,
                'iso2' => 'CY',
                'iso3' => 'CYP',
                'name' => 'Cyprus',
                'name_de' => 'Zypern',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 55,
                'iso2' => 'CZ',
                'iso3' => 'CZE',
                'name' => 'Czech Republic',
                'name_de' => 'Tschechische Republik',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 56,
                'iso2' => 'DE',
                'iso3' => 'DEU',
                'name' => 'Germany',
                'name_de' => 'Deutschland',
                'priority' => 1,
                'is_published' => 1,
            ],
            [
                'id' => 57,
                'iso2' => 'DJ',
                'iso3' => 'DJI',
                'name' => 'Djibouti',
                'name_de' => 'Republik Dschibuti',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 58,
                'iso2' => 'DK',
                'iso3' => 'DNK',
                'name' => 'Denmark',
                'name_de' => 'Dänemark',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 59,
                'iso2' => 'DM',
                'iso3' => 'DMA',
                'name' => 'Dominica',
                'name_de' => 'Dominica',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 60,
                'iso2' => 'DO',
                'iso3' => 'DOM',
                'name' => 'Dominican Republic',
                'name_de' => 'Dominikanische Republik',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 61,
                'iso2' => 'DZ',
                'iso3' => 'DZA',
                'name' => 'Algeria',
                'name_de' => 'Algerien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 62,
                'iso2' => 'EC',
                'iso3' => 'ECU',
                'name' => 'Ecuador',
                'name_de' => 'Ecuador',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 63,
                'iso2' => 'EE',
                'iso3' => 'EST',
                'name' => 'Estonia',
                'name_de' => 'Estland',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 64,
                'iso2' => 'EG',
                'iso3' => 'EGY',
                'name' => 'Egypt',
                'name_de' => 'Ägypten',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 65,
                'iso2' => 'EH',
                'iso3' => 'ESH',
                'name' => 'Western Sahara',
                'name_de' => 'Westsahara',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 66,
                'iso2' => 'ER',
                'iso3' => 'ERI',
                'name' => 'Eritrea',
                'name_de' => 'Eritrea',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 67,
                'iso2' => 'ES',
                'iso3' => 'ESP',
                'name' => 'Spain',
                'name_de' => 'Spanien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 68,
                'iso2' => 'ET',
                'iso3' => 'ETH',
                'name' => 'Ethiopia',
                'name_de' => 'Äthiopien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 69,
                'iso2' => 'FI',
                'iso3' => 'FIN',
                'name' => 'Finland',
                'name_de' => 'Finnland',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 70,
                'iso2' => 'FJ',
                'iso3' => 'FJI',
                'name' => 'Fiji',
                'name_de' => 'Fidschi',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 71,
                'iso2' => 'FK',
                'iso3' => 'FLK',
                'name' => 'Falkland Islands (Malvinas)',
                'name_de' => 'Falklandinseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 72,
                'iso2' => 'FM',
                'iso3' => 'FSM',
                'name' => 'Micronesia, Federated States of',
                'name_de' => 'Mikronesien, Föderierte Staaten von',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 73,
                'iso2' => 'FO',
                'iso3' => 'FRO',
                'name' => 'Faroe Islands',
                'name_de' => 'Färöer',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 74,
                'iso2' => 'FR',
                'iso3' => 'FRA',
                'name' => 'France',
                'name_de' => 'Frankreich',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 75,
                'iso2' => 'GA',
                'iso3' => 'GAB',
                'name' => 'Gabon',
                'name_de' => 'Gabun',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 76,
                'iso2' => 'GB',
                'iso3' => 'GBR',
                'name' => 'United Kingdom',
                'name_de' => 'Vereinigtes Königreich',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 77,
                'iso2' => 'GD',
                'iso3' => 'GRD',
                'name' => 'Grenada',
                'name_de' => 'Grenada',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 78,
                'iso2' => 'GE',
                'iso3' => 'GEO',
                'name' => 'Georgia',
                'name_de' => 'Georgien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 79,
                'iso2' => 'GF',
                'iso3' => 'GUF',
                'name' => 'French Guiana',
                'name_de' => 'Französisch Guiana',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 80,
                'iso2' => 'GG',
                'iso3' => 'GGY',
                'name' => 'Guernsey',
                'name_de' => 'Guernsey',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 81,
                'iso2' => 'GH',
                'iso3' => 'GHA',
                'name' => 'Ghana',
                'name_de' => 'Ghana',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 82,
                'iso2' => 'GI',
                'iso3' => 'GIB',
                'name' => 'Gibraltar',
                'name_de' => 'Gibraltar',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 83,
                'iso2' => 'GL',
                'iso3' => 'GRL',
                'name' => 'Greenland',
                'name_de' => 'Grönland',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 84,
                'iso2' => 'GM',
                'iso3' => 'GMB',
                'name' => 'Gambia',
                'name_de' => 'Gambia',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 85,
                'iso2' => 'GN',
                'iso3' => 'GIN',
                'name' => 'Guinea',
                'name_de' => 'Guinea',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 86,
                'iso2' => 'GP',
                'iso3' => 'GLP',
                'name' => 'Guadeloupe',
                'name_de' => 'Guadeloupe',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 87,
                'iso2' => 'GQ',
                'iso3' => 'GNQ',
                'name' => 'Equatorial Guinea',
                'name_de' => 'Äquatorialguinea',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 88,
                'iso2' => 'GR',
                'iso3' => 'GRC',
                'name' => 'Greece',
                'name_de' => 'Griechenland',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 89,
                'iso2' => 'GS',
                'iso3' => 'SGS',
                'name' => 'South Georgia and The South Sandwich Islands',
                'name_de' => 'Südgeorgien und die Südlichen Sandwichinseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 90,
                'iso2' => 'GT',
                'iso3' => 'GTM',
                'name' => 'Guatemala',
                'name_de' => 'Guatemala',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 91,
                'iso2' => 'GU',
                'iso3' => 'GUM',
                'name' => 'Guam',
                'name_de' => 'Guam',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 92,
                'iso2' => 'GW',
                'iso3' => 'GNB',
                'name' => 'Guinea-bissau',
                'name_de' => 'Guinea-Bissau',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 93,
                'iso2' => 'GY',
                'iso3' => 'GUY',
                'name' => 'Guyana',
                'name_de' => 'Guyana',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 94,
                'iso2' => 'HK',
                'iso3' => 'HKG',
                'name' => 'Hong Kong',
                'name_de' => 'Hong Kong',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 95,
                'iso2' => 'HM',
                'iso3' => 'HMD',
                'name' => 'Heard Island and Mcdonald Islands',
                'name_de' => 'Heard Insel und McDonald Inseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 96,
                'iso2' => 'HN',
                'iso3' => 'HND',
                'name' => 'Honduras',
                'name_de' => 'Honduras',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 97,
                'iso2' => 'HR',
                'iso3' => 'HRV',
                'name' => 'Croatia',
                'name_de' => 'Kroatien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 98,
                'iso2' => 'HT',
                'iso3' => 'HTI',
                'name' => 'Haiti',
                'name_de' => 'Haiti',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 99,
                'iso2' => 'HU',
                'iso3' => 'HUN',
                'name' => 'Hungary',
                'name_de' => 'Ungarn',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 100,
                'iso2' => 'ID',
                'iso3' => 'IDN',
                'name' => 'Indonesia',
                'name_de' => 'Indonesien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 101,
                'iso2' => 'IE',
                'iso3' => 'IRL',
                'name' => 'Ireland',
                'name_de' => 'Irland',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 102,
                'iso2' => 'IL',
                'iso3' => 'ISR',
                'name' => 'Israel',
                'name_de' => 'Israel',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 103,
                'iso2' => 'IM',
                'iso3' => 'IMN',
                'name' => 'Isle of Man',
                'name_de' => 'Isle of Man',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 104,
                'iso2' => 'IN',
                'iso3' => 'IND',
                'name' => 'India',
                'name_de' => 'Indien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 105,
                'iso2' => 'IO',
                'iso3' => 'IOT',
                'name' => 'British Indian Ocean Territory',
                'name_de' => 'Britische Territorien im Indischen Ozean',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 106,
                'iso2' => 'IQ',
                'iso3' => 'IRQ',
                'name' => 'Iraq',
                'name_de' => 'Irak',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 107,
                'iso2' => 'IR',
                'iso3' => 'IRN',
                'name' => 'Iran, Islamic Republic of',
                'name_de' => 'Iran, Islam. Rep.',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 108,
                'iso2' => 'IS',
                'iso3' => 'ISL',
                'name' => 'Iceland',
                'name_de' => 'Island',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 109,
                'iso2' => 'IT',
                'iso3' => 'ITA',
                'name' => 'Italy',
                'name_de' => 'Italien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 110,
                'iso2' => 'JE',
                'iso3' => 'JEY',
                'name' => 'Jersey',
                'name_de' => 'Jersey',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 111,
                'iso2' => 'JM',
                'iso3' => 'JAM',
                'name' => 'Jamaica',
                'name_de' => 'Jamaika',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 112,
                'iso2' => 'JO',
                'iso3' => 'JOR',
                'name' => 'Jordan',
                'name_de' => 'Jordanien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 113,
                'iso2' => 'JP',
                'iso3' => 'JPN',
                'name' => 'Japan',
                'name_de' => 'Japan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 114,
                'iso2' => 'KE',
                'iso3' => 'KEN',
                'name' => 'Kenya',
                'name_de' => 'Kenia',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 115,
                'iso2' => 'KG',
                'iso3' => 'KGZ',
                'name' => 'Kyrgyzstan',
                'name_de' => 'Kirgisistan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 116,
                'iso2' => 'KH',
                'iso3' => 'KHM',
                'name' => 'Cambodia',
                'name_de' => 'Kambodscha',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 117,
                'iso2' => 'KI',
                'iso3' => 'KIR',
                'name' => 'Kiribati',
                'name_de' => 'Kiribati',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 118,
                'iso2' => 'KM',
                'iso3' => 'COM',
                'name' => 'Comoros',
                'name_de' => 'Komoren',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 119,
                'iso2' => 'KN',
                'iso3' => 'KNA',
                'name' => 'Saint Kitts and Nevis',
                'name_de' => 'St. Kitts und Nevis',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 120,
                'iso2' => 'KP',
                'iso3' => 'PRK',
                'name' => 'Korea, Democratic People\'s Republic of',
                'name_de' => 'Korea, Dem. Volksrep.',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 121,
                'iso2' => 'KR',
                'iso3' => 'KOR',
                'name' => 'Korea, Republic of',
                'name_de' => 'Korea, Rep.',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 122,
                'iso2' => 'KW',
                'iso3' => 'KWT',
                'name' => 'Kuwait',
                'name_de' => 'Kuwait',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 123,
                'iso2' => 'KY',
                'iso3' => 'CYM',
                'name' => 'Cayman Islands',
                'name_de' => 'Kaimaninseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 124,
                'iso2' => 'KZ',
                'iso3' => 'KAZ',
                'name' => 'Kazakhstan',
                'name_de' => 'Kasachstan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 125,
                'iso2' => 'LA',
                'iso3' => 'LAO',
                'name' => 'Lao People\'s Democratic Republic',
                'name_de' => 'Laos, Dem. Volksrep.',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 126,
                'iso2' => 'LB',
                'iso3' => 'LBN',
                'name' => 'Lebanon',
                'name_de' => 'Libanon',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 127,
                'iso2' => 'LC',
                'iso3' => 'LCA',
                'name' => 'Saint Lucia',
                'name_de' => 'St. Lucia',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 128,
                'iso2' => 'LI',
                'iso3' => 'LIE',
                'name' => 'Liechtenstein',
                'name_de' => 'Liechtenstein',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 129,
                'iso2' => 'LK',
                'iso3' => 'LKA',
                'name' => 'Sri Lanka',
                'name_de' => 'Sri Lanka',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 130,
                'iso2' => 'LR',
                'iso3' => 'LBR',
                'name' => 'Liberia',
                'name_de' => 'Liberia',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 131,
                'iso2' => 'LS',
                'iso3' => 'LSO',
                'name' => 'Lesotho',
                'name_de' => 'Lesotho',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 132,
                'iso2' => 'LT',
                'iso3' => 'LTU',
                'name' => 'Lithuania',
                'name_de' => 'Litauen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 133,
                'iso2' => 'LU',
                'iso3' => 'LUX',
                'name' => 'Luxembourg',
                'name_de' => 'Luxemburg',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 134,
                'iso2' => 'LV',
                'iso3' => 'LVA',
                'name' => 'Latvia',
                'name_de' => 'Lettland',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 135,
                'iso2' => 'LY',
                'iso3' => 'LBY',
                'name' => 'Libyan Arab Jamahiriya',
                'name_de' => 'Libysch-Arabische Dschamahirija',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 136,
                'iso2' => 'MA',
                'iso3' => 'MAR',
                'name' => 'Morocco',
                'name_de' => 'Marokko',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 137,
                'iso2' => 'MC',
                'iso3' => 'MCO',
                'name' => 'Monaco',
                'name_de' => 'Monaco',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 138,
                'iso2' => 'MD',
                'iso3' => 'MDA',
                'name' => 'Moldova, Republic of',
                'name_de' => 'Moldau, Rep.',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 139,
                'iso2' => 'ME',
                'iso3' => 'MNE',
                'name' => 'Montenegro',
                'name_de' => 'Montenegro',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 140,
                'iso2' => 'MF',
                'iso3' => 'MAF',
                'name' => 'St. Martin',
                'name_de' => 'St. Martin',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 141,
                'iso2' => 'MG',
                'iso3' => 'MDG',
                'name' => 'Madagascar',
                'name_de' => 'Madagaskar',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 142,
                'iso2' => 'MH',
                'iso3' => 'MHL',
                'name' => 'Marshall Islands',
                'name_de' => 'Marshallinseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 143,
                'iso2' => 'MK',
                'iso3' => 'MKD',
                'name' => 'Macedonia, The Former Yugoslav Republic of',
                'name_de' => 'Mazedonien, ehemalige jugoslawische Republik',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 144,
                'iso2' => 'ML',
                'iso3' => 'MLI',
                'name' => 'Mali',
                'name_de' => 'Mali',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 145,
                'iso2' => 'MM',
                'iso3' => 'MMR',
                'name' => 'Myanmar',
                'name_de' => 'Myanmar',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 146,
                'iso2' => 'MN',
                'iso3' => 'MNG',
                'name' => 'Mongolia',
                'name_de' => 'Mongolei',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 147,
                'iso2' => 'MO',
                'iso3' => 'MAC',
                'name' => 'Macao',
                'name_de' => 'Macao',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 148,
                'iso2' => 'MP',
                'iso3' => 'MNP',
                'name' => 'Northern Mariana Islands',
                'name_de' => 'Nördliche Marianen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 149,
                'iso2' => 'MQ',
                'iso3' => 'MTQ',
                'name' => 'Martinique',
                'name_de' => 'Martinique',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 150,
                'iso2' => 'MR',
                'iso3' => 'MRT',
                'name' => 'Mauritania',
                'name_de' => 'Mauretanien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 151,
                'iso2' => 'MS',
                'iso3' => 'MSR',
                'name' => 'Montserrat',
                'name_de' => 'Montserrat',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 152,
                'iso2' => 'MT',
                'iso3' => 'MLT',
                'name' => 'Malta',
                'name_de' => 'Malta',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 153,
                'iso2' => 'MU',
                'iso3' => 'MUS',
                'name' => 'Mauritius',
                'name_de' => 'Mauritius',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 154,
                'iso2' => 'MV',
                'iso3' => 'MDV',
                'name' => 'Maldives',
                'name_de' => 'Malediven',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 155,
                'iso2' => 'MW',
                'iso3' => 'MWI',
                'name' => 'Malawi',
                'name_de' => 'Malawi',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 156,
                'iso2' => 'MX',
                'iso3' => 'MEX',
                'name' => 'Mexico',
                'name_de' => 'Mexiko',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 157,
                'iso2' => 'MY',
                'iso3' => 'MYS',
                'name' => 'Malaysia',
                'name_de' => 'Malaysia',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 158,
                'iso2' => 'MZ',
                'iso3' => 'MOZ',
                'name' => 'Mozambique',
                'name_de' => 'Mosambik',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 159,
                'iso2' => 'NA',
                'iso3' => 'NAM',
                'name' => 'Namibia',
                'name_de' => 'Namibia',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 160,
                'iso2' => 'NC',
                'iso3' => 'NCL',
                'name' => 'New Caledonia',
                'name_de' => 'Neukaledonien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 161,
                'iso2' => 'NE',
                'iso3' => 'NER',
                'name' => 'Niger',
                'name_de' => 'Niger',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 162,
                'iso2' => 'NF',
                'iso3' => 'NFK',
                'name' => 'Norfolk Island',
                'name_de' => 'Norfolk Insel',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 163,
                'iso2' => 'NG',
                'iso3' => 'NGA',
                'name' => 'Nigeria',
                'name_de' => 'Nigeria',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 164,
                'iso2' => 'NI',
                'iso3' => 'NIC',
                'name' => 'Nicaragua',
                'name_de' => 'Nicaragua',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 165,
                'iso2' => 'NL',
                'iso3' => 'NLD',
                'name' => 'Netherlands',
                'name_de' => 'Niederlande',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 166,
                'iso2' => 'NO',
                'iso3' => 'NOR',
                'name' => 'Norway',
                'name_de' => 'Norwegen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 167,
                'iso2' => 'NP',
                'iso3' => 'NPL',
                'name' => 'Nepal',
                'name_de' => 'Nepal',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 168,
                'iso2' => 'NR',
                'iso3' => 'NRU',
                'name' => 'Nauru',
                'name_de' => 'Nauru',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 169,
                'iso2' => 'NU',
                'iso3' => 'NIU',
                'name' => 'Niue',
                'name_de' => 'Niue',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 170,
                'iso2' => 'NZ',
                'iso3' => 'NZL',
                'name' => 'New Zealand',
                'name_de' => 'Neuseeland',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 171,
                'iso2' => 'OM',
                'iso3' => 'OMN',
                'name' => 'Oman',
                'name_de' => 'Oman',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 172,
                'iso2' => 'PA',
                'iso3' => 'PAN',
                'name' => 'Panama',
                'name_de' => 'Panama',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 173,
                'iso2' => 'PE',
                'iso3' => 'PER',
                'name' => 'Peru',
                'name_de' => 'Peru',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 174,
                'iso2' => 'PF',
                'iso3' => 'PYF',
                'name' => 'French Polynesia',
                'name_de' => 'Französisch Polynesien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 175,
                'iso2' => 'PG',
                'iso3' => 'PNG',
                'name' => 'Papua New Guinea',
                'name_de' => 'Papua-Neuguinea',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 176,
                'iso2' => 'PH',
                'iso3' => 'PHL',
                'name' => 'Philippines',
                'name_de' => 'Philippinen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 177,
                'iso2' => 'PK',
                'iso3' => 'PAK',
                'name' => 'Pakistan',
                'name_de' => 'Pakistan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 178,
                'iso2' => 'PL',
                'iso3' => 'POL',
                'name' => 'Poland',
                'name_de' => 'Polen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 179,
                'iso2' => 'PM',
                'iso3' => 'SPM',
                'name' => 'Saint Pierre and Miquelon',
                'name_de' => 'Saint Pierre und Miquelon',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 180,
                'iso2' => 'PN',
                'iso3' => 'PCN',
                'name' => 'Pitcairn',
                'name_de' => 'Pitcairn',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 181,
                'iso2' => 'PR',
                'iso3' => 'PRI',
                'name' => 'Puerto Rico',
                'name_de' => 'Puerto Rico',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 182,
                'iso2' => 'PS',
                'iso3' => 'PSE',
                'name' => 'Palestinian Territory, Occupied',
                'name_de' => 'Palästinische Gebiete',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 183,
                'iso2' => 'PT',
                'iso3' => 'PRT',
                'name' => 'Portugal',
                'name_de' => 'Portugal',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 184,
                'iso2' => 'PW',
                'iso3' => 'PLW',
                'name' => 'Palau',
                'name_de' => 'Palau',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 185,
                'iso2' => 'PY',
                'iso3' => 'PRY',
                'name' => 'Paraguay',
                'name_de' => 'Paraguay',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 186,
                'iso2' => 'QA',
                'iso3' => 'QAT',
                'name' => 'Qatar',
                'name_de' => 'Katar',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 187,
                'iso2' => 'RE',
                'iso3' => 'REU',
                'name' => 'Reunion',
                'name_de' => 'Réunion',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 188,
                'iso2' => 'RO',
                'iso3' => 'ROU',
                'name' => 'Romania',
                'name_de' => 'Rumänien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 189,
                'iso2' => 'RS',
                'iso3' => 'SRB',
                'name' => 'Serbia',
                'name_de' => 'Serbien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 190,
                'iso2' => 'RU',
                'iso3' => 'RUS',
                'name' => 'Russian Federation',
                'name_de' => 'Russische Föderation',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 191,
                'iso2' => 'RW',
                'iso3' => 'RWA',
                'name' => 'Rwanda',
                'name_de' => 'Ruanda',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 192,
                'iso2' => 'SA',
                'iso3' => 'SAU',
                'name' => 'Saudi Arabia',
                'name_de' => 'Saudi-Arabien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 193,
                'iso2' => 'SB',
                'iso3' => 'SLB',
                'name' => 'Solomon Islands',
                'name_de' => 'Salomonen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 194,
                'iso2' => 'SC',
                'iso3' => 'SYC',
                'name' => 'Seychelles',
                'name_de' => 'Seychellen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 195,
                'iso2' => 'SD',
                'iso3' => 'SDN',
                'name' => 'Sudan',
                'name_de' => 'Sudan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 196,
                'iso2' => 'SE',
                'iso3' => 'SWE',
                'name' => 'Sweden',
                'name_de' => 'Schweden',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 197,
                'iso2' => 'SG',
                'iso3' => 'SGP',
                'name' => 'Singapore',
                'name_de' => 'Singapur',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 198,
                'iso2' => 'SH',
                'iso3' => 'SHN',
                'name' => 'Saint Helena',
                'name_de' => 'Saint Helena',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 199,
                'iso2' => 'SI',
                'iso3' => 'SVN',
                'name' => 'Slovenia',
                'name_de' => 'Slowenien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 200,
                'iso2' => 'SJ',
                'iso3' => 'SJM',
                'name' => 'Svalbard and Jan Mayen',
                'name_de' => 'Svalbard und Jan Mayen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 201,
                'iso2' => 'SK',
                'iso3' => 'SVK',
                'name' => 'Slovakia',
                'name_de' => 'Slowakei',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 202,
                'iso2' => 'SL',
                'iso3' => 'SLE',
                'name' => 'Sierra Leone',
                'name_de' => 'Sierra Leone',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 203,
                'iso2' => 'SM',
                'iso3' => 'SMR',
                'name' => 'San Marino',
                'name_de' => 'San Marino',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 204,
                'iso2' => 'SN',
                'iso3' => 'SEN',
                'name' => 'Senegal',
                'name_de' => 'Senegal',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 205,
                'iso2' => 'SO',
                'iso3' => 'SOM',
                'name' => 'Somalia',
                'name_de' => 'Somalia',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 206,
                'iso2' => 'SR',
                'iso3' => 'SUR',
                'name' => 'Suriname',
                'name_de' => 'Suriname',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 207,
                'iso2' => 'ST',
                'iso3' => 'STP',
                'name' => 'Sao Tome and Principe',
                'name_de' => 'SA£o Tomé und PrA­ncipe',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 208,
                'iso2' => 'SV',
                'iso3' => 'SLV',
                'name' => 'El Salvador',
                'name_de' => 'El Salvador',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 209,
                'iso2' => 'SY',
                'iso3' => 'SYR',
                'name' => 'Syrian Arab Republic',
                'name_de' => 'Syrien, Arab. Rep.',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 210,
                'iso2' => 'SZ',
                'iso3' => 'SWZ',
                'name' => 'Swaziland',
                'name_de' => 'Swasiland',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 211,
                'iso2' => 'TC',
                'iso3' => 'TCA',
                'name' => 'Turks and Caicos Islands',
                'name_de' => 'Turks- und Caicosinseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 212,
                'iso2' => 'TD',
                'iso3' => 'TCD',
                'name' => 'Chad',
                'name_de' => 'Tschad',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 213,
                'iso2' => 'TF',
                'iso3' => 'ATF',
                'name' => 'French Southern Territories',
                'name_de' => 'Französische Südgebiete',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 214,
                'iso2' => 'TG',
                'iso3' => 'TGO',
                'name' => 'Togo',
                'name_de' => 'Togo',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 215,
                'iso2' => 'TH',
                'iso3' => 'THA',
                'name' => 'Thailand',
                'name_de' => 'Thailand',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 216,
                'iso2' => 'TJ',
                'iso3' => 'TJK',
                'name' => 'Tajikistan',
                'name_de' => 'Tadschikistan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 217,
                'iso2' => 'TK',
                'iso3' => 'TKL',
                'name' => 'Tokelau',
                'name_de' => 'Tokelau',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 218,
                'iso2' => 'TL',
                'iso3' => 'TLS',
                'name' => 'Timor-leste',
                'name_de' => 'Timor-Leste',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 219,
                'iso2' => 'TM',
                'iso3' => 'TKM',
                'name' => 'Turkmenistan',
                'name_de' => 'Turkmenistan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 220,
                'iso2' => 'TN',
                'iso3' => 'TUN',
                'name' => 'Tunisia',
                'name_de' => 'Tunesien',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 221,
                'iso2' => 'TO',
                'iso3' => 'TON',
                'name' => 'Tonga',
                'name_de' => 'Tonga',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 222,
                'iso2' => 'TR',
                'iso3' => 'TUR',
                'name' => 'Turkey',
                'name_de' => 'Türkei',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 223,
                'iso2' => 'TT',
                'iso3' => 'TTO',
                'name' => 'Trinidad and Tobago',
                'name_de' => 'Trinidad und Tobago',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 224,
                'iso2' => 'TV',
                'iso3' => 'TUV',
                'name' => 'Tuvalu',
                'name_de' => 'Tuvalu',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 225,
                'iso2' => 'TW',
                'iso3' => 'TWN',
                'name' => 'Taiwan, Province of China',
                'name_de' => 'Taiwan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 226,
                'iso2' => 'TZ',
                'iso3' => 'TZA',
                'name' => 'Tanzania, United Republic of',
                'name_de' => 'Tansania, Vereinigte Rep.',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 227,
                'iso2' => 'UA',
                'iso3' => 'UKR',
                'name' => 'Ukraine',
                'name_de' => 'Ukraine',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 228,
                'iso2' => 'UG',
                'iso3' => 'UGA',
                'name' => 'Uganda',
                'name_de' => 'Uganda',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 229,
                'iso2' => 'UM',
                'iso3' => 'UMI',
                'name' => 'United States Minor Outlying Islands',
                'name_de' => 'United States Minor Outlying Islands',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 230,
                'iso2' => 'US',
                'iso3' => 'USA',
                'name' => 'United States',
                'name_de' => 'Vereinigte Staaten von Amerika',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 231,
                'iso2' => 'UY',
                'iso3' => 'URY',
                'name' => 'Uruguay',
                'name_de' => 'Uruguay',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 232,
                'iso2' => 'UZ',
                'iso3' => 'UZB',
                'name' => 'Uzbekistan',
                'name_de' => 'Usbekistan',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 233,
                'iso2' => 'VA',
                'iso3' => 'VAT',
                'name' => 'Holy See (Vatican City State)',
                'name_de' => 'Heiliger Stuhl',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 234,
                'iso2' => 'VC',
                'iso3' => 'VCT',
                'name' => 'Saint Vincent and The Grenadines',
                'name_de' => 'St. Vincent und die Grenadinen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 235,
                'iso2' => 'VE',
                'iso3' => 'VEN',
                'name' => 'Venezuela',
                'name_de' => 'Venezuela',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 236,
                'iso2' => 'VG',
                'iso3' => 'VGB',
                'name' => 'Virgin Islands, British',
                'name_de' => 'Britische Jungferninseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 237,
                'iso2' => 'VI',
                'iso3' => 'VIR',
                'name' => 'Virgin Islands, U.S.',
                'name_de' => 'Amerikanische Jungferninseln',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 238,
                'iso2' => 'VN',
                'iso3' => 'VNM',
                'name' => 'Viet Nam',
                'name_de' => 'Vietnam',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 239,
                'iso2' => 'VU',
                'iso3' => 'VUT',
                'name' => 'Vanuatu',
                'name_de' => 'Vanuatu',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 240,
                'iso2' => 'WF',
                'iso3' => 'WLF',
                'name' => 'Wallis and Futuna',
                'name_de' => 'Wallis und Futuna',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 241,
                'iso2' => 'WS',
                'iso3' => 'WSM',
                'name' => 'Samoa',
                'name_de' => 'Samoa',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 242,
                'iso2' => 'YE',
                'iso3' => 'YEM',
                'name' => 'Yemen',
                'name_de' => 'Jemen',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 243,
                'iso2' => 'YT',
                'iso3' => 'MYT',
                'name' => 'Mayotte',
                'name_de' => 'Mayotte',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 244,
                'iso2' => 'ZA',
                'iso3' => 'ZAF',
                'name' => 'South Africa',
                'name_de' => 'Südafrika',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 245,
                'iso2' => 'ZM',
                'iso3' => 'ZMB',
                'name' => 'Zambia',
                'name_de' => 'Sambia',
                'priority' => 0,
                'is_published' => 0,
            ],
            [
                'id' => 246,
                'iso2' => 'ZW',
                'iso3' => 'ZWE',
                'name' => 'Zimbabwe',
                'name_de' => 'Simbabwe',
                'priority' => 0,
                'is_published' => 0,
            ],
        ];

        $table = $this->table('shop_countries');
        $table->insert($data)->save();
    }
}
